#### Shared Information

# Master Server Hostname
master_server: "{{ NBU_MASTER_SERVER }}"

# API - Information
nbu_api_hostname: "{{ master_server }}"
nbu_api_port: '1556'
nbu_api_base_url: "{{ 'https://' + nbu_api_hostname + ':' + nbu_api_port + '/netbackup/' }}"
nbu_api_content_type: application/vnd.netbackup+json;version=5.0;charset=UTF-8

#### MSDP - Local

# Disk Pool - Storage Server
msdp_local_ss_hostname: "{{ inventory_hostname_short }}"
msdp_local_ss_encryption: true
msdp_local_ss_kmsenabled: true
msdp_local_ss_dir_db: /msdp/db
msdp_local_ss_dir_data: /msdp/data

# Storage Server - Security / Encryption
msdp_local_ss_kmskeygroup: '{{ nbu_kms_kg_name }}'              # Tower
msdp_local_ss_username: '{{ nbu_admin_user }}'                  # Tower
msdp_local_ss_password: '{{ nbu_admin_password }}'              # Tower

# Disk Pool - Disk Pool
msdp_local_dp_name: "dp_msdp_local_{{ inventory_hostname_short }}"
msdp_local_dp_volume: PureDiskVolume
msdp_local_dp_io: 100
msdp_local_dp_id: "PureDisk:{{inventory_hostname_short}}"

# Storage Unit - Information
msdp_local_stu_name: "stu_msdp_local_{{ inventory_hostname_short }}"
msdp_local_stu_mediaservers: "{{ inventory_hostname_short }}"
msdp_local_stu_io: 80
msdp_local_stu_ondemand: true
msdp_local_stu_id: "PureDisk:{{msdp_local_dp_name}}"

#### MSDP - Cloud

# AWS
aws_access_key: '{{ aws_access_key }}'
aws_access_secret: '{{ aws_secret_key }}'

# Storage Server
msdp_cloud_ss_ssl_mode: DATA
msdp_cloud_ss_ssl_crl: true
msdp_cloud_ss_ssl_http: '0'
msdp_cloud_ss_ssl_https: '0'

# Disk Pool - Disk Pool
msdp_cloud_dp_name: "dp_msdp_cloud_aws_{{ inventory_hostname_short }}"
msdp_cloud_dp_io: 100
msdp_cloud_dp_id: "PureDisk:{{ inventory_hostname_short }}"
msdp_cloud_dp_encryption: true
msdp_cloud_dp_kmsenabled: true
msdp_cloud_dp_ssl_mode: DATA
msdp_cloud_dp_ssl_crl: true
msdp_cloud_dp_ssl_http: '0'
msdp_cloud_dp_ssl_https: '0'

# Storage Unit - Information
msdp_cloud_stu_name: "stu_msdp_cloud_aws_{{ inventory_hostname_short }}"
msdp_cloud_stu_mediaservers: "{{ inventory_hostname_short }}"
msdp_cloud_stu_io: 80
msdp_cloud_stu_id: "PureDisk:{{msdp_cloud_dp_name}}"

# KMS
msdp_cloud_dp_kmskeygroup: '{{ nbu_kms_kg_name }}'