- name: Select VM and list backups
  hosts: localhost
  vars:
    nbu_api_content_type:
      application/vnd.netbackup+json;version=5.0;charset=UTF-8
    NBU_API_KEY:
      A8fmNjyB5DvvzAN1CnRWblMv160U1Vt5hs5P2fqj81pJh9224HRus-w9YuXnwSMa
    nbu_api_hostname:
      nbumaster.lab.local
    nbu_api_baseurl:
       "https://{{ nbu_api_hostname }}:1556/netbackup"
    asset_id:
      84ba26e1-bd89-45c6-9ad4-196b0d8f9287

  tasks:
    - name: Query discovered VMs
      uri:
        url: "{{ nbu_api_baseurl }}/asset-service/workloads/vmware/assets?page%5Blimit%5D=10&page%5Bdisable%5D=true"
        method: GET
        headers:
          Content-Type: "{{ nbu_api_content_type }}"
          Authorization: "{{ NBU_API_KEY }}"
        validate_certs: False
        timeout: "300"
        status_code:
          - 200
          - 400
          - 401
          - 404
          - 500
      register:
          result1

    - name: Print VM fields
      debug:
        msg:
          - "displayName: {{item.attributes.commonAssetAttributes.displayName | default(-1) }}"
          - "id (referenced by NBU): {{item.id | default(-1) }}"
          - "instanceUuid: {{item.attributes.instanceUuid | default(-1) }}"
          - "assetType: {{item.attributes.assetType | default(-1) }}"
          - "vCenter: {{item.attributes.vCenter | default(-1) }}"
          - "vmAbsolutePath: {{item.attributes.vmAbsolutePath | default(-1) }}"
          - "vmxDatastore: {{item.attributes.vmxDatastore | default(-1) }}"
          - "lastDiscoveredTime: {{item.attributes.commonAssetAttributes.detection.lastDiscoveredTime | default(-1)}}"
          - "nicIpAddresses: {{item.attributes.nicIpAddresses| default(-1) }}"
      loop:  "{{result1.json.data }}"
      loop_control:
        index_var: my_idx
        label: "{{ my_idx }}"

    - name: Query singe VM data by assetId (Backups since 1st Nov 2021)
      uri:
        url: "{{ nbu_api_baseurl }}/recovery-point-service/workloads/vmware/recovery-points?page%5Blimit%5D=100&page%5Boffset%5D=0&filter=assetId+eq+%27{{asset_id}}%27+and+%28backupTime+ge+2021-11-01T00%3A00%3A00.000Z%29&include=optionalVmwareRecoveryPointInfo"
        method: GET
        headers:
          Content-Type: "{{ nbu_api_content_type }}"
          Authorization: "{{ NBU_API_KEY }}"
        validate_certs: False
        timeout: "300"
        status_code:
          - 200
          - 400
          - 401
          - 404
          - 500
      register:
          result2

#    - name: Print full response
#      debug:
#        msg:
#         #  Innstall this filter first! Run: ansible-galaxy collection install ansible.utils
#         - "{{ lookup( 'ansible.utils.to_paths', result2.json) }}"

    - name: Print Asset results
      debug:
        msg:
          - "BackupTime: {{item.attributes.backupTime}}"
          - "BackupId: {{item.id}}"
          - "JobId: {{item.attributes.extendedAttributes.imageAttributes.jobId}}"
          - "copyNumber:  {{item.attributes.extendedAttributes.imageAttributes.fragments[0].copyNumber}}"
      loop:  "{{result2.json.data }}"
      loop_control:
        index_var: my_idx2
        label: "id (referenced by NBU): {{ asset_id }} recovery point: {{ my_idx2 }}"
