
- name: List active instant access mountpoints
  hosts: localhost
  vars:
    nbu_api_content_type:
      application/vnd.netbackup+json;version=5.0;charset=UTF-8
    NBU_API_KEY:
      A8fmNjyB5DvvzAN1CnRWblMv160U1Vt5hs5P2fqj81pJh9224HRus-w9YuXnwSMa
    nbu_api_hostname:
      nbumaster.lab.local
    nbu_api_baseurl:
       https://nbumaster.lab.local:1556/netbackup
#      https://{{ nbu_api_hostname }}:1556/netbackup

  tasks:
    - name: Get instant access mount points
      uri:
        url: https://nbumaster.lab.local:1556/netbackup/recovery/workloads/vmware/instant-access-vms
#          url: "{{ nbu_api_baseurl }}"/recovery/workloads/vmware/instant-access-vms
        method: GET
        headers:
          Content-Type: "{{ nbu_api_content_type }}"
          Authorization: "{{ NBU_API_KEY }}"
        validate_certs: False
        timeout: "300"
        status_code:
          - 200
          - 400
          - 401
          - 404
          - 500
      register:
          result1
      debugger:
        on_failed

    - name: Print result
      debug:
        var: result1.json
