- name: -> Get Asset ID
  uri:
    url: https://{{ nbu_api_hostname }}:1556/netbackup//asset-service/workloads/{{slo_workload}}/assets?filter=clientName%20eq%20%27{{slo_client}}%27
    method: GET
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
      Authorization: "{{ NBU_API_KEY }}"  
    validate_certs: False
    timeout: "300"
    status_code:
      - 200
      - 400
      - 401
      - 404
      - 500
  register: vm_list

- name: -> Set Asset ID as fact
  set_fact:
    assetid: "{{ vm_list.json.data[0].id }}"  
 
