- name: -> Set NetBackup Catalog DR Policy Password
  shell: |
         ( echo "{{ master_server }}"; echo "0"; echo unixpwd; echo "{{ NBU_CLI_USER_NAME }}"; echo "{{ NBU_CLI_USER_PASSWORD }}") |  /usr/openv/netbackup/bin/bpnbat -login -loginType WEB
         (echo "{{ NBU_DR_FILE_PASSWORD }}"; echo "{{ NBU_DR_FILE_PASSWORD }}" ) | /usr/openv/netbackup/bin/admincmd/nbseccmd -drpkgpassphrase
  register: set_dr_password
  run_once: true
  changed_when: set_dr_password.rc == 0
  failed_when: 
    - set_dr_password.rc != 89
    - set_dr_password.rc != 0
  tags:
    - nbu_master_config_drpasswd

