- name: -> Create NetBackup Disk Pool ("MSDP - Local") - Create filesytem directories
  file:
    path: '{{item}}'
    state: directory
  with_items:
    - /msdp/db
    - /msdp/data
  tags:
    - nbu_msdp_local_create
    - nbu_msdp_local_create_ss

- name: -> Create NetBackup Disk Pool ("MSDP - Local") - Storage Server
  uri:
    url: https://{{ nbu_api_hostname }}:1556/netbackup/storage/storage-servers
    method: POST
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
      Authorization: "{{ NBU_API_KEY }}"  
    body: "{{ lookup('template', 'msdp_local_storageserver.j2') }}"
    body_format: json
    validate_certs: False
    timeout: 60
    status_code:
      - 201
      - 400
      - 401
      - 409
      - 500
  register: result
  changed_when: result.status != 409
  failed_when: result.status not in [201, 409]
  retries: 5
  delay: 2
  until:  result.status == 201 or result.status == 409
  tags:
    - nbu_msdp_local_create
    - nbu_msdp_local_create_ss