- name: -> Update NetBackup Disk Pool ("MSDP - AWS") - Storage Server
  uri:
    url: https://{{ nbu_api_hostname }}:1556/netbackup/storage/storage-servers/PureDisk:{{ inventory_hostname_short }}/cloud-buckets
    method: POST
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
      Authorization: "{{ NBU_API_KEY }}" 
    body: "{{ lookup('template', 'msdp_cloud_storageserver.j2') }}"
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 400
      - 401
      - 409
      - 500
  register: result
  changed_when: result.status not in [201, 409]
  failed_when: result.status not in [201, 400, 409]
  retries: 5
  delay: 2
  until:  result.status == 201 or result.status == 409 or result.status == 400
  tags:
    - nbu_msdp_cloud_create
    - nbu_msdp_cloud_create_ss