- name: -> Get authorization token from NetBackup API
  uri:
    url: "{{ nbu_api_base_url + 'login' }}"
    method: POST
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
    body: "{{ lookup('template', 'nbu_api_creds.j2') }}"
    body_format: json
    status_code: 201, 401
    validate_certs: no
  register: task_nbu_get_auth_token_result
  retries: 5
  delay: 2
  until:  task_nbu_get_auth_token_result.status == 201
  tags:
    - nbu_api_token_get

- name: -> Set authorization token from NetBackup API as fact
  set_fact:
    NBU_TOKEN: "{{ task_nbu_get_auth_token_result.json.token }}"
  tags:
    - nbu_api_token_get